//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastUpdatedRecord
    {
        public int LastUpdatedID { get; set; }
        public int EmpNumber { get; set; }
        public int MachineNO { get; set; }
        public int VerifyMode { get; set; }
        public int LYear { get; set; }
        public int LMonth { get; set; }
        public int LDay { get; set; }
        public Nullable<int> LHour { get; set; }
        public string LMinute { get; set; }
        public string LSecond { get; set; }
    
        public virtual LastUpdatedRecord LastUpdatedRecord1 { get; set; }
        public virtual LastUpdatedRecord LastUpdatedRecord2 { get; set; }
    }
}
