//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string EmpName { get; set; }
        public string Designation { get; set; }
        public System.DateTime WDate { get; set; }
        public Nullable<int> Late { get; set; }
        public Nullable<int> DayDeduct { get; set; }
    }
}
