//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AttendanceLog
    {
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<System.TimeSpan> InsideOfficeDuration { get; set; }
        public Nullable<System.TimeSpan> OutsideOfficeDuration { get; set; }
        public System.DateTime WDate { get; set; }
        public int Id { get; set; }
        public int EmpID { get; set; }
    }
}
